2025-07-13 at 14:33:53 | ERROR | Attempt 1/3 failed: name 'url' is not defined
2025-07-13 at 14:33:55 | ERROR | Attempt 2/3 failed: name 'url' is not defined
2025-07-13 at 14:33:59 | ERROR | Attempt 3/3 failed: name 'url' is not defined
2025-07-13 at 14:41:40 | ERROR | Attempt 1/3 failed: name 'url' is not defined
2025-07-13 at 14:41:42 | ERROR | Attempt 2/3 failed: name 'url' is not defined
2025-07-13 at 14:41:46 | ERROR | Attempt 3/3 failed: name 'url' is not defined
2025-07-13 at 14:42:39 | ERROR | Attempt 1/3 failed: name 'url' is not defined
2025-07-13 at 14:42:41 | ERROR | Attempt 2/3 failed: name 'url' is not defined
2025-07-13 at 14:42:45 | ERROR | Attempt 3/3 failed: name 'url' is not defined
2025-07-16 at 21:04:13 | ERROR | Attempt 1/3 failed: HTTPConnectionPool(host='100.100.20.144', port=9997): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x106cd49e0>, 'Connection to 100.100.20.144 timed out. (connect timeout=None)'))
2025-07-16 at 21:05:51 | ERROR | Attempt 2/3 failed: HTTPConnectionPool(host='100.100.20.144', port=9997): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x106cd4ad0>, 'Connection to 100.100.20.144 timed out. (connect timeout=None)'))
2025-07-16 at 21:08:01 | ERROR | Attempt 3/3 failed: HTTPConnectionPool(host='100.100.20.144', port=9997): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x106cd5400>, 'Connection to 100.100.20.144 timed out. (connect timeout=None)'))
